Repository thalees/statements-control, pull requests merged in 2019-05, with the labels that each got.

#1 Create vos
  statements-control/Library/Class1.cs
  statements-control/Library/Library.csproj
  statements-control/Library/Properties/AssemblyInfo.cs
  statements-control/Library/VOs/MasterVO.cs
  statements-control/statements-control/fr_Sobre.Designer.cs
  statements-control/statements-control/fr_Sobre.cs
Labels: enhancement

#5 Library
  statements-control/Library/DAOs/ConnectionDB.cs
  statements-control/Library/ENUMs/MessageTypeENUM.cs
  statements-control/Library/ENUMs/NavigationTypeENUM.cs
  statements-control/Library/GlobalVariables.cs
  statements-control/Library/Library.csproj
  statements-control/Library/Methods.cs
  statements-control/Library/Properties/AssemblyInfo.cs
  statements-control/statements-control.sln
Labels: enhancement

#7 Library
  statements-control/Library/DAOs/ConnectionDB.cs
  statements-control/Library/DAOs/EnvironmentsDAO.cs
  statements-control/Library/DAOs/GoalsDAO.cs
  statements-control/Library/DAOs/InvestmentsDAO.cs
  statements-control/Library/DAOs/MasterDAO.cs
  statements-control/Library/DAOs/StatementsDAO.cs
  statements-control/Library/DAOs/TypesDAO.cs
  statements-control/Library/DAOs/UsersDAO.cs
  statements-control/Library/ENUMs/MessageTypeENUM.cs
  statements-control/Library/ENUMs/NavigationTypeENUM.cs
  statements-control/Library/GlobalVariables.cs
  statements-control/Library/Library.csproj
  statements-control/Library/Methods.cs
  statements-control/Library/Properties/AssemblyInfo.cs
  statements-control/Library/VOs/EnvironmentsVO.cs
  statements-control/Library/VOs/GoalsVO.cs
  statements-control/Library/VOs/InvestmentsVO.cs
  statements-control/Library/VOs/MasterVO.cs
  statements-control/Library/VOs/StatementsVO.cs
  statements-control/Library/VOs/TypesVO.cs
  statements-control/Library/VOs/UsersVO.cs
  statements-control/statements-control.sln
Labels: enhancement

#10 Name mastervo
  statements-control/Library/VOs/EnvironmentsVO.cs
  statements-control/Library/VOs/GoalsVO.cs
  statements-control/Library/VOs/InvestmentsVO.cs
  statements-control/Library/VOs/MasterVO.cs
  statements-control/Library/VOs/UsersVO.cs
  statements-control/statements-control/statements-control.csproj
  statements-control/statements-control/uc_TypesRegister.Designer.cs
  statements-control/statements-control/uc_TypesRegister.cs
Labels: enhancement

#11 Functions for the database
  statements-control/Database/Database.csproj
  statements-control/Database/Functions/Goals.sql
  statements-control/Database/Stored Procedures/Goals.sql
Labels: enhancement

#12 Cursors for the database
  statements-control/Database/Cursors/Cursors.sql
  statements-control/Database/Database.csproj
Labels: enhancement

#13 Triggers for the database
  statements-control/Database/Database.csproj
  statements-control/Database/Triggers/DeleteEnvironment.sql
  statements-control/Database/Triggers/DeleteType.sql
  statements-control/Database/Triggers/DeleteUser.sql
Labels: enhancement

#9 Database Structure
  statements-control/Database/Cursors/Cursors.sql
  statements-control/Database/Database.csproj
  statements-control/Database/Functions/Goals.sql
  statements-control/Database/Indexes/ActionTypes.sql
  statements-control/Database/Indexes/UserIdGoals.sql
  statements-control/Database/Initializer/CreateTables.sql
  statements-control/Database/Initializer/Seeds.sql
  statements-control/Database/Properties/AssemblyInfo.cs
  statements-control/Database/Stored Procedures/Database.sql
  statements-control/Database/Stored Procedures/Environments.sql
  statements-control/Database/Stored Procedures/Investments.sql
  statements-control/Database/Stored Procedures/Statements.sql
  statements-control/Database/Stored Procedures/Types.sql
  statements-control/Database/Stored Procedures/Users.sql
  statements-control/Database/Triggers/DeleteEnvironment.sql
  statements-control/Database/Triggers/DeleteType.sql
  statements-control/Database/Triggers/DeleteUser.sql
  statements-control/statements-control.sln
Labels: Don't merge, enhancement

#17 Added a method that instantiates databases.
  statements-control/Database/Cursors/Cursors.sql
  statements-control/Database/Functions/Goals.sql
  statements-control/Database/Indexes/ActionTypes.sql
  statements-control/Database/Indexes/UserIdGoals.sql
  statements-control/Database/Initializer/CreateTables.sql
  statements-control/Database/Initializer/Seeds.sql
  statements-control/Database/Stored Procedures/Database.sql
  statements-control/Database/Stored Procedures/Environments.sql
  statements-control/Database/Stored Procedures/Investments.sql
  statements-control/Database/Stored Procedures/Statements.sql
  statements-control/Database/Stored Procedures/Types.sql
  statements-control/Database/Stored Procedures/Users.sql
  statements-control/Database/Triggers/DeleteEnvironment.sql
  statements-control/Database/Triggers/DeleteType.sql
  statements-control/Database/Triggers/DeleteUser.sql
  statements-control/Library/DAOs/EnvironmentsDAO.cs
  statements-control/Library/DAOs/GoalsDAO.cs
  statements-control/Library/DAOs/InvestmentsDAO.cs
  statements-control/Library/DAOs/MasterDAO.cs
  statements-control/Library/DAOs/StatementsDAO.cs
  statements-control/Library/DAOs/TypesDAO.cs
  statements-control/Library/DAOs/UsersDAO.cs
  statements-control/statements-control/fr_DataBaseParameters.cs
Labels: Don't merge, enhancement

#16 Fixed the bug in the decryption process.
  statements-control/statements-control/fr_Login.cs
Labels: bug

#21 Reformulated DAOs to correct bugs on insert/update
  statements-control/Library/DAOs/EnvironmentsDAO.cs
  statements-control/Library/DAOs/GoalsDAO.cs
  statements-control/Library/DAOs/InvestmentsDAO.cs
  statements-control/Library/DAOs/MasterDAO.cs
  statements-control/Library/DAOs/StatementsDAO.cs
  statements-control/Library/DAOs/TypesDAO.cs
  statements-control/Library/DAOs/UsersDAO.cs
  statements-control/Library/ENUMs/ActionDBENUM.cs
  statements-control/Library/Library.csproj
Labels: bug

#22 Added temporary table into procedure
  statements-control/Database/Cursors/Cursors.sql
Labels: enhancement
